apiVersion: v1
kind: Service
metadata:
  name: selemene-ts-engines
  labels:
    app: selemene
    component: ts-engines
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  selector:
    app: selemene
    component: ts-engines
